# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='common.proto',
  package='apt2d8.common',
  serialized_pb='\n\x0c\x63ommon.proto\x12\rapt2d8.common\"6\n\x07Version\x12\r\n\x05major\x18\x01 \x02(\r\x12\r\n\x05minor\x18\x02 \x02(\r\x12\r\n\x05patch\x18\x03 \x02(\r\"\x95\x01\n\x0c\x44istribution\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x14\n\x0c\x61rchitecture\x18\x02 \x02(\t\x12\x1d\n\x15\x66oreign_architectures\x18\x03 \x03(\t\x12\n\n\x02id\x18\x04 \x01(\t\x12\x0f\n\x07release\x18\x05 \x01(\t\x12\x10\n\x08\x63odename\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\"<\n\x06Kernel\x12\x0e\n\x06ostype\x18\x01 \x01(\t\x12\x11\n\tosrelease\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"\x8d\x01\n\x06Source\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61seuri\x18\x03 \x01(\t\x12\x0c\n\x04\x64ist\x18\x04 \x01(\t\x12.\n\x05\x63omps\x18\x05 \x03(\x0b\x32\x1f.apt2d8.common.Source.Component\x1a\x19\n\tComponent\x12\x0c\n\x04name\x18\x01 \x02(\t\"\x88\x04\n\x06\x43hange\x12.\n\x07package\x18\x01 \x02(\x0b\x32\x1d.apt2d8.common.Change.Package\x12\x32\n\toperation\x18\x02 \x02(\x0e\x32\x1f.apt2d8.common.Change.Operation\x1a\x81\x01\n\x07Package\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x33\n\tinstalled\x18\x02 \x01(\x0b\x32 .apt2d8.common.Change.PkgVersion\x12\x33\n\tcandidate\x18\x03 \x01(\x0b\x32 .apt2d8.common.Change.PkgVersion\x1a\xba\x01\n\nPkgVersion\x12\x0f\n\x07version\x18\x01 \x02(\t\x12\x14\n\x0c\x61rchitecture\x18\x02 \x01(\t\x12\x0e\n\x06origin\x18\x03 \x01(\t\x12\x0f\n\x07\x61rchive\x18\x04 \x01(\t\x12\x11\n\tcomponent\x18\x05 \x01(\t\x12\x0c\n\x04size\x18\x06 \x01(\x04\x12\x16\n\x0einstalled_size\x18\x07 \x01(\x04\x12\x13\n\x0bsource_name\x18\x08 \x01(\t\x12\x16\n\x0esource_version\x18\t \x01(\t\"Y\n\tOperation\x12\x0b\n\x07INSTALL\x10\x00\x12\r\n\tREINSTALL\x10\x01\x12\x0b\n\x07UPGRADE\x10\x02\x12\r\n\tDOWNGRADE\x10\x03\x12\n\n\x06REMOVE\x10\x04\x12\x08\n\x04KEEP\x10\x05')



_CHANGE_OPERATION = descriptor.EnumDescriptor(
  name='Operation',
  full_name='apt2d8.common.Change.Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='INSTALL', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REINSTALL', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UPGRADE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DOWNGRADE', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REMOVE', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='KEEP', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=877,
  serialized_end=966,
)


_VERSION = descriptor.Descriptor(
  name='Version',
  full_name='apt2d8.common.Version',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='major', full_name='apt2d8.common.Version.major', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='minor', full_name='apt2d8.common.Version.minor', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='patch', full_name='apt2d8.common.Version.patch', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=85,
)


_DISTRIBUTION = descriptor.Descriptor(
  name='Distribution',
  full_name='apt2d8.common.Distribution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='apt2d8.common.Distribution.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='architecture', full_name='apt2d8.common.Distribution.architecture', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='foreign_architectures', full_name='apt2d8.common.Distribution.foreign_architectures', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='apt2d8.common.Distribution.id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='release', full_name='apt2d8.common.Distribution.release', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='codename', full_name='apt2d8.common.Distribution.codename', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='apt2d8.common.Distribution.description', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=88,
  serialized_end=237,
)


_KERNEL = descriptor.Descriptor(
  name='Kernel',
  full_name='apt2d8.common.Kernel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ostype', full_name='apt2d8.common.Kernel.ostype', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='osrelease', full_name='apt2d8.common.Kernel.osrelease', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version', full_name='apt2d8.common.Kernel.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=239,
  serialized_end=299,
)


_SOURCE_COMPONENT = descriptor.Descriptor(
  name='Component',
  full_name='apt2d8.common.Source.Component',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='apt2d8.common.Source.Component.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=418,
  serialized_end=443,
)

_SOURCE = descriptor.Descriptor(
  name='Source',
  full_name='apt2d8.common.Source',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='apt2d8.common.Source.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='uri', full_name='apt2d8.common.Source.uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='baseuri', full_name='apt2d8.common.Source.baseuri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dist', full_name='apt2d8.common.Source.dist', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='comps', full_name='apt2d8.common.Source.comps', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SOURCE_COMPONENT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=302,
  serialized_end=443,
)


_CHANGE_PACKAGE = descriptor.Descriptor(
  name='Package',
  full_name='apt2d8.common.Change.Package',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='apt2d8.common.Change.Package.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='installed', full_name='apt2d8.common.Change.Package.installed', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='candidate', full_name='apt2d8.common.Change.Package.candidate', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=557,
  serialized_end=686,
)

_CHANGE_PKGVERSION = descriptor.Descriptor(
  name='PkgVersion',
  full_name='apt2d8.common.Change.PkgVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='apt2d8.common.Change.PkgVersion.version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='architecture', full_name='apt2d8.common.Change.PkgVersion.architecture', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='origin', full_name='apt2d8.common.Change.PkgVersion.origin', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='archive', full_name='apt2d8.common.Change.PkgVersion.archive', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='component', full_name='apt2d8.common.Change.PkgVersion.component', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='size', full_name='apt2d8.common.Change.PkgVersion.size', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='installed_size', full_name='apt2d8.common.Change.PkgVersion.installed_size', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='source_name', full_name='apt2d8.common.Change.PkgVersion.source_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='source_version', full_name='apt2d8.common.Change.PkgVersion.source_version', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=689,
  serialized_end=875,
)

_CHANGE = descriptor.Descriptor(
  name='Change',
  full_name='apt2d8.common.Change',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='package', full_name='apt2d8.common.Change.package', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='operation', full_name='apt2d8.common.Change.operation', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CHANGE_PACKAGE, _CHANGE_PKGVERSION, ],
  enum_types=[
    _CHANGE_OPERATION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=446,
  serialized_end=966,
)

_SOURCE_COMPONENT.containing_type = _SOURCE;
_SOURCE.fields_by_name['comps'].message_type = _SOURCE_COMPONENT
_CHANGE_PACKAGE.fields_by_name['installed'].message_type = _CHANGE_PKGVERSION
_CHANGE_PACKAGE.fields_by_name['candidate'].message_type = _CHANGE_PKGVERSION
_CHANGE_PACKAGE.containing_type = _CHANGE;
_CHANGE_PKGVERSION.containing_type = _CHANGE;
_CHANGE.fields_by_name['package'].message_type = _CHANGE_PACKAGE
_CHANGE.fields_by_name['operation'].enum_type = _CHANGE_OPERATION
_CHANGE_OPERATION.containing_type = _CHANGE;
DESCRIPTOR.message_types_by_name['Version'] = _VERSION
DESCRIPTOR.message_types_by_name['Distribution'] = _DISTRIBUTION
DESCRIPTOR.message_types_by_name['Kernel'] = _KERNEL
DESCRIPTOR.message_types_by_name['Source'] = _SOURCE
DESCRIPTOR.message_types_by_name['Change'] = _CHANGE

class Version(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VERSION
  
  # @@protoc_insertion_point(class_scope:apt2d8.common.Version)

class Distribution(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DISTRIBUTION
  
  # @@protoc_insertion_point(class_scope:apt2d8.common.Distribution)

class Kernel(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KERNEL
  
  # @@protoc_insertion_point(class_scope:apt2d8.common.Kernel)

class Source(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Component(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SOURCE_COMPONENT
    
    # @@protoc_insertion_point(class_scope:apt2d8.common.Source.Component)
  DESCRIPTOR = _SOURCE
  
  # @@protoc_insertion_point(class_scope:apt2d8.common.Source)

class Change(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Package(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CHANGE_PACKAGE
    
    # @@protoc_insertion_point(class_scope:apt2d8.common.Change.Package)
  
  class PkgVersion(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CHANGE_PKGVERSION
    
    # @@protoc_insertion_point(class_scope:apt2d8.common.Change.PkgVersion)
  DESCRIPTOR = _CHANGE
  
  # @@protoc_insertion_point(class_scope:apt2d8.common.Change)

# @@protoc_insertion_point(module_scope)
